services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: no
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
    ports:
      - "5432:5432"
    volumes:
      - ../../datas/postgres-data:/var/lib/postgresql/data
