# 마리아DB
services:
  mariadb:
    image: mariadb:11.7
    container_name: mariadb
    restart: no
    environment:
      - MARIADB_ROOT_PASSWORD=""  # 비밀번호를 설정하지 않으려면 빈 문자열로 설정
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes  # 비밀번호 없이 root 접속 허용
      - MARIADB_DATABASE=dbname  # 기본 데이터베이스 이름
      - MARIADB_USER=dbuser  # 기본 사용자 이름
      - MARIADB_PASSWORD=dbpassword  # 사용자 비밀번호
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/init db.d:/docker-entrypoint-init db.d
    ports:
      - "3306:3306"
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --lower_case_table_names=1
      --bind-address=0.0.0.0  # 외부 접속 가능
