services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    restart: no
    ports:
      - "3000:8080"
    volumes:
      - ../../datas/webui-data:/app/backend/data